# Generated by Django 2.2.1 on 2019-05-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotify',
            name='node',
        ),
        migrations.RemoveField(
            model_name='usernotify',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserNotify',
        ),
    ]
