# Generated by Django 2.2.1 on 2019-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190526_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='allowedDowntime',
            field=models.IntegerField(default=60),
        ),
    ]
