# Generated by Django 2.2.1 on 2019-05-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_node_alloweddowntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='battCritical',
            field=models.FloatField(default=0.0, help_text='Battery level at which to send critical messages'),
        ),
        migrations.AddField(
            model_name='node',
            name='battLevel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='battMonitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='battName',
            field=models.CharField(blank=True, help_text='Name of JSON attribute that contains battery level', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='battWarn',
            field=models.FloatField(default=0.0, help_text='Battery level at which to send warning messages'),
        ),
        migrations.AlterField(
            model_name='node',
            name='allowedDowntime',
            field=models.IntegerField(default=60, help_text="Minutes that the node can be 'unheard' before being marked as Offline"),
        ),
    ]
