# Generated by Django 2.2.1 on 2019-05-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190527_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='RSSI',
            field=models.FloatField(default=0.0, help_text='Received Signal Strength Indicator'),
        ),
    ]
