# Generated by Django 2.2.1 on 2019-06-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_node_rssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='battStatus',
            field=models.CharField(default=' ', help_text="'G' for good, 'W' for warning, 'C' for critically low, ' ' for not monitored", max_length=1),
        ),
    ]
